---
title: 'Other News'
teaching: 10
exercises: 2
---


## Augmented reality connecting humans with non-humans

We are running a workshop online in conjunction with the [University of Universities](https://uou.ua.es). 

The workshop offers the opportunity to work alongside students from other countries and other universities in the evolution of conceptual ideas for an augmented reality project which seeks to further connect us with the non-humans we share our spaces with. 

The students are from architecture courses.
 
The workshop will consist of three sessions: 

- Session 1 (Friday 6th Oct 2023, 12:00): a short half hour introduction on , which also sets out the first task which is to be completed before the second session – this will be used to place the students into groups. 
- Session 2 (Friday 13th 8:30 - 12:30): includes a discussion of task one, various talks from researchers on AI and AR,
and time for working within the group of students they are assigned to on ideas for a project. 
- Session 3 (Friday, 27th October)"
The final session is on the following Friday, 27th October: involve a review of the project work – which will be a story board of the ideas for the project and final drawings.

For more information, [see here](files/UOUSSInterweavings.pdf).
 
## Final Year Projects

Looking to supervise CI601 projects on:

- Artificial Intelligence driven classification/analysis of large-scale multi-dimensional media, such as images/3D/4D. See [related project by my lab](https://culturedigitalskills.org/news/ai-methods-large-scale-images/).
- Digitisation and video analysis of intangible skills via ego-centric video. See related work on [hand detection on ego-centric video by my lab](https://www.dropbox.com/s/7k569q4eajld8p1/vis_smallGoProAVCencoder1920x108011m47s_000036-converted.mp4){alt="video hands detection"}
- Immersive 360 digitisation – Insta 360/Go Pro
- Interactive visualisation of large-scale multi-dimensional media, e.g. virtual and augmented reality. See relevant [work here by Sarah Kenderdine](https://epfl-pavilions.ch/exhibitions/infinity-room-2). 
- Web-interoperability of multidimensional media via IIIF
- Computer vision and graphics algorithms for 3D printing and broader applications in particular to Cultural Heritage


::::::::::::::::::::::::::::::::::::: keypoints 

- Various activities are available in parallel to the module
should you wish to get further involved.
::::::::::::::::::::::::::::::::::::::::::::::::



