---
title: 'Resources'
teaching: 10
exercises: 2
---

## MyStudies/StudentCentral
- Slides are available in MyStudies.
- Tutorials will also be made available every week.
- Other announcements will be made by email.Check this regularly. 

## Development platforms

- You don’t need equipment, as we have headsets and visualisation kit at the University
- For WebVR -  you can use a smartphone:
  - For VR Google Cardboard  - you'll need an Android device running Android 4.4 'KitKat' (API level 19) or higher, and a Cardboard viewer (https://arvr.google.com/cardboard/get-cardboard/).
  - For AR you can also use ARKit, which requires an iOS device with iOS 11.0 or later.


## Virtual Reality laboratory
- Space for experimenting and developing VR applications.
- Watts 623
- HTC Vive, Virtualizer Elite 2 motion platform, and mixed reality headsets are available

## Immersive Learning Visualisation Suite
Igloo front project 3D system, Advanced Engineering Centre, 101

Equipment:
- 8 x 5000 lumen HD/WUXGA UST projectors with 3D (projected on four walls).
- 2 x 5100 lumens HD/WUXGA projectors with 3D (projected on the floor).
- IMP III Media player
- 5.1 Surround Sound system
- An 3D stereoscopic Igloo
- Server cabinet with network switch plus peripherals
- 10 x 3D glasses and 3D emitter
- Igloo Elite Software Package
- 8 PrimeX 13 OptiTrack Camera Systems
- OptiTrack MOTIVE Body Software
- T3D Mocap Suit - Summer- Men - MEDIUM - Black/Blue
- OptiTrack Marker Set 14mm w/ X-Base

## Reading list
- Most required resources will be given using the module material.
- Other extra resources will be available in the reading list.

## Asking for help
- Things never run smoothly.
- If you need help, you can contact:
  - Myself
  - Course leader.
  - Student support and guidance tutor.
  - Technical support team at the computer suite.
  - School office team will help you with everything to do with your course administration.

