---
title: 'Skills and knowledge'
teaching: 10
exercises: 2
---



## What will we learn in this module?
In this module we will work together to develop and gain 1) Theoretical knowledge and 2) practical experience

 techniques and technologies employed for building 
Extended Reality (XR) systems,
including - but not restricted to - Virtual Reality systems. 

## Which techniques and technologies?

The techniques and technologies we will cover
include software tools, hardware devices, libraries and  algorithms for 
creating, manipulating and rendering spatial+immersive and interactive 
systems.

These systems can be experienced using Mixed-Reality equipment (but not only).

Most of these systems require knowledge in subjects such as 
computer graphics and multidimensional data which includes
2D and 3D data.


## How will the module enhance your CV

Even if you are not planning to work in the XR or the game industry, this module


- Better understanding of the potential of visual environments work in various application areas.
- Better awareness of technologies to acquire, process and interact with visual content.
- Skills to developing systems to visualise and manipulate visual information through mixed reality technologies.







