---
title: 'Tutorial: Research on Extended Reality Systems'
teaching: 10
exercises: 2
---

::::::::::::::::::::::::::::::::::::: objectives

- To explore a variety of XR experiences that are in the market.
- To brainstorm some ideas to develop within the module.
- To oversee state of the art techniques and technologies.

::::::::::::::::::::::::::::::::::::::::::::::::

## Introduction

This tutorial will involve researching existing applications in XR systems,
and start building an understanding of the challenges involved 
in their creation.

Your task will be to produce a presentation, it can be presented in any visual
format you wish (e.g. an image, a video or a 3D environment - such as [Mozilla Hubs](https://hubs.mozilla.com/).


## What do you need to do?
You can either focus on:

1 - Look at graphic projects you might already have available, e.g. projects
you might have done before in Unity and Unreal that you think you can build on.

3 - Exploring the XR applications available on a platform, such as a VR platforms 
such as STEAM, Oculus Store,
or a mobile app store: Google Play, etc.


3 - Exploring the literature in the area, for example in leading conferences, magazines and journals in the
area of Computer Graphics as we saw in this lesson. The papers can be related to platforms, 
techniques (e.g. interaction or content creation) or applications.



In any case, it would be good to place particular attention to the challenges
involved in developing such experience.
So might brainstorm what is the process to create such system and what type of
content you might need to use.

## What do you need to prepare?

For next tutorial, you will need to present your research. This will involve
preparing a summary or demo of the research you have done.

In the presentation, please identify:

- scope of this research, 
- why you selected it, and how you envisage it could be used,
- the components of the system, 
- the process you believe is involved in building it,
- the type of interactions with the content, 
- the challenges involved in developing such system.

Don't forget to cite the paper, application or other reference; and provide a link to it.

::::::::::::::::::::::::::::::::::::: keypoints 

- This tutorial involves researching what is available in the lab and in the market.

::::::::::::::::::::::::::::::::::::::::::::::::

